"""Iae

Revision ID: 50430d518f37
Revises: 9e6c516929a0
Create Date: 2022-08-27 17:19:35.076003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50430d518f37'
down_revision = '9e6c516929a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_accounts', sa.Column('sobrenome', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_accounts', 'sobrenome')
    # ### end Alembic commands ###
