"""Iae

Revision ID: 9e6c516929a0
Revises: 
Create Date: 2022-08-27 17:11:51.145367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6c516929a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user')
    )
    op.create_table('tb_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sender', sa.Integer(), nullable=False),
    sa.Column('id_receiver', sa.Integer(), nullable=False),
    sa.Column('hora_transacao', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_receiver'], ['tb_accounts.id'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['tb_accounts.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_sender', 'id_receiver')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_transactions')
    op.drop_table('tb_accounts')
    op.drop_table('tb_users')
    # ### end Alembic commands ###
