"""Iae

Revision ID: b7a81d2d59ed
Revises: 50430d518f37
Create Date: 2022-08-27 18:20:43.212388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7a81d2d59ed'
down_revision = '50430d518f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.drop_column('tb_accounts', 'sobrenome')
    op.add_column('tb_transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('tb_transactions', 'hora_transacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_transactions', sa.Column('hora_transacao', mysql.DATETIME(), nullable=False))
    op.drop_column('tb_transactions', 'created_at')
    op.add_column('tb_accounts', sa.Column('sobrenome', mysql.VARCHAR(length=200), nullable=False))
    op.drop_table('tb_profiles')
    # ### end Alembic commands ###
