"""empty message

Revision ID: 7c157b54127d
Revises: a3bea37f7398
Create Date: 2022-08-20 17:42:42.940914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c157b54127d'
down_revision = 'a3bea37f7398'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users')
    op.drop_table('tb_orders')
    op.drop_table('tb_order_details')
    op.drop_table('tb_users_profiles')
    op.drop_table('tb_products')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_products',
    sa.Column('id_product', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id_product'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_users_profiles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('birth_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_users.id'], name='tb_users_profiles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_order_details',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_product', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quant', mysql.FLOAT(), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['tb_orders.id_order'], name='tb_order_details_ibfk_2'),
    sa.ForeignKeyConstraint(['id_product'], ['tb_products.id_product'], name='tb_order_details_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'id_product'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_orders',
    sa.Column('id_order', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tb_users.id'], name='tb_orders_ibfk_1'),
    sa.PrimaryKeyConstraint('id_order', 'id_user'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
